### ISSUE TITLE
Internal server error when list of patients and their task schedules

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#151]
Only seen this once:
```

[2021-04-01 15:30:39 +0100] [2514180] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 332, in secured_view
    raise HTTPForbidden(msg, result=result)
pyramid.httpexceptions.HTTPForbidden: Unauthorized: main_menu failed permission check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_pyramid.py", line 528, in __call__
    result = template.render_unicode(**system)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/template.py", line 479, in render_unicode
    self, self.callable_, args, data, as_unicode=True
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "base_mako", line 69, in render_body
  File "base_web_mako", line 70, in render_body
  File "forbidden_mako", line 41, in render_body
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 795, in _include_file
    callable_(ctx, **kwargs)
  File "db_user_info_mako", line 30, in render_body
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 1401, in database_title
    ss = self.server_settings
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 1394, in server_settings
    return get_server_settings(self)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_serversettings.py", line 216, in get_server_settings
    .filter(ServerSettings.id == SERVER_SETTINGS_SINGLETON_PK)\
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3397, in first
    ret = list(self[0:1])
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3171, in __getitem__
    return list(res)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 686, in _key_fallback
    replace_context=err,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column '_server_settings.id'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/cardinal_pythonlib/wsgi/reverse_proxied_mw.py", line 553, in __call__
    return self.app(environ, start_response)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/cardinal_pythonlib/wsgi/headers_mw.py", line 132, in __call__
    return self.app(environ, custom_start_response)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/view.py", line 767, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 275, in wrapper
    response = view(context, request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/webview.py", line 754, in forbidden
    request=req)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/renderers.py", line 138, in render_to_response
    result = helper.render_to_response(value, None, request=request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/renderers.py", line 474, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/renderers.py", line 470, in render
    result = renderer(value, system_values)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_pyramid.py", line 534, in __call__
    reraise(MakoRenderingException(errtext), None, exc_info[2])
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid_mako/compat.py", line 74, in reraise
    raise value.with_traceback(tb)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_pyramid.py", line 528, in __call__
    result = template.render_unicode(**system)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/template.py", line 479, in render_unicode
    self, self.callable_, args, data, as_unicode=True
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "base_mako", line 69, in render_body
  File "base_web_mako", line 70, in render_body
  File "forbidden_mako", line 41, in render_body
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 795, in _include_file
    callable_(ctx, **kwargs)
  File "db_user_info_mako", line 30, in render_body
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 1401, in database_title
    ss = self.server_settings
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 1394, in server_settings
    return get_server_settings(self)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_serversettings.py", line 216, in get_server_settings
    .filter(ServerSettings.id == SERVER_SETTINGS_SINGLETON_PK)\
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3397, in first
    ret = list(self[0:1])
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3171, in __getitem__
    return list(res)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 686, in _key_fallback
    replace_context=err,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
pyramid_mako.MakoRenderingException:

Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_pyramid.py", line 528, in __call__
    result = template.render_unicode(**system)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/template.py", line 479, in render_unicode
    self, self.callable_, args, data, as_unicode=True
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/templates/base/base.mako", line 59, in render_body
    ${next.body()}
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/templates/base/base_web.mako", line 73, in render_body
    ${next.body()}
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/templates/menu/forbidden.mako", line 35, in render_body
    <%include file="db_user_info.mako"/>
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/mako/runtime.py", line 795, in _include_file
    callable_(ctx, **kwargs)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/templates/snippets/db_user_info.mako", line 34, in render_body
    ${_("Database")}: <b>${ request.database_title | h }</b>.
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 1401, in database_title
    ss = self.server_settings
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 1394, in server_settings
    return get_server_settings(self)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_serversettings.py", line 216, in get_server_settings
    .filter(ServerSettings.id == SERVER_SETTINGS_SINGLETON_PK)\
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3397, in first
    ret = list(self[0:1])
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3171, in __getitem__
    return list(res)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 686, in _key_fallback
    replace_context=err,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
NoSuchColumnError: "Could not locate column in row for column '_server_settings.id'"

[2021-04-01 15:30:39 +0100] [2514184] [ERROR] Error handling request /view_patient_task_schedules
Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 731, in get
    return dict_[key]
KeyError: 'user_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/cardinal_pythonlib/wsgi/reverse_proxied_mw.py", line 553, in __call__
    return self.app(environ, start_response)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/cardinal_pythonlib/wsgi/headers_mw.py", line 132, in __call__
    return self.app(environ, custom_start_response)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 323, in secured_view
    result = permitted(context, request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 319, in permitted
    principals = authn_policy.effective_principals(request)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_pyramid.py", line 1058, in effective_principals
    user = request.user
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 1282, in user
    return self._debugging_user or self.camcops_session.user
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 287, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 723, in get
    value = self.callable_(state, passive)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 727, in _load_for_state
    session, state, passive
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 775, in _get_ident_for_use_get
    for pk in self.mapper.primary_key
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 775, in <listcomp>
    for pk in self.mapper.primary_key
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 2826, in _get_state_attr_by_column
    return state.manager[prop.key].impl.get(state, dict_, passive=passive)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 740, in get
    replace_context=err,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
KeyError: "Deferred loader for attribute 'user_id' failed to populate correctly"
```

**Comment by RudolfCardinal** [comment]
Failed to replicate lots; closing.
