### ISSUE TITLE
Incorrect datetime value for column 'indexed_at_utc' when reindexing with pymysql

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#155]
I'm getting this error on latest master after rebuilding my virtualenv and reindexing:

```
(camcops) [12:11:11 tools]$ camcops_server reindex
2021-04-16 12:11:15.432 [p8324.t140244592617280] camcops_server.camcops_server:INFO:
# =============================================================================
# CamCOPS server version 2.4.4
# Created by Rudolf Cardinal. See https://camcops.readthedocs.io/
# =============================================================================

2021-04-16 12:11:15.432 [p8324.t140244592617280] camcops_server.camcops_server:INFO: Using configuration file: '/home/martinb/workspace/camcops/working/camcops.cfg'
2021-04-16 12:11:15.432 [p8324.t140244592617280] camcops_server.cc_modules.cc_config:INFO: Reading from config file: '/home/martinb/workspace/camcops/working/camcops.cfg'
2021-04-16 12:11:15.435 [p8324.t140244592617280] camcops_server.camcops_server_core:INFO: Imports starting
2021-04-16 12:11:21.563 [p8324.t140244592617280] camcops_server.camcops_server_core:INFO: Imports complete
2021-04-16 12:11:21.565 [p8324.t140244592617280] camcops_server.camcops_server_core:INFO: Using 126 tasks
2021-04-16 12:11:21.583 [p8324.t140244592617280] cardinal_pythonlib.sqlalchemy.alembic_func:INFO: Intended database version: 0062
2021-04-16 12:11:21.593 [p8324.t140244592617280] alembic.runtime.migration:INFO: Context impl MySQLImpl.
2021-04-16 12:11:21.593 [p8324.t140244592617280] alembic.runtime.migration:INFO: Will assume non-transactional DDL.
2021-04-16 12:11:21.595 [p8324.t140244592617280] cardinal_pythonlib.sqlalchemy.alembic_func:INFO: Current database version: 0062
2021-04-16 12:11:21.595 [p8324.t140244592617280] camcops_server.cc_modules.cc_taskindex:INFO: Reindexing database; indexed_at_utc = 2021-04-16T11:11:21.595551+00:00
2021-04-16 12:11:21.595 [p8324.t140244592617280] camcops_server.cc_modules.cc_taskindex:INFO: Rebuilding patient ID number index
Traceback (most recent call last):
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/martinb/.virtualenvs/camcops/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1292, "Incorrect datetime value: '2021-04-16T11:11:21.595551+00:00' for column 'indexed_at_utc' at row 1")

```
Only a problem with PyMySQL, not a problem with mysqlclient. I'm assuming it's MySQL not liking the +00:00

I thought this was perhaps related to a newer version of PyMySQL but downgrading makes no difference.

#2 is similar but related to mysqlclient rather than pymysql

@RudolfCardinal are you using PyMySQL locally? Is reindex working for you on latest master?

**Comment by RudolfCardinal** [comment]
I think now fixed (in fhir-dev now). Changelog entry:

- Bugfix for hacking the ``pymysql`` driver to support Pendulum date/time objects properly. The bug manifested during reindexing, and was as documented above in :ref:`v2.3.3 <changelog_v2_3_3>`.

... which was the same error. Closing.
