### ISSUE TITLE
Patient registration initially failed on CPFT server following switch back to UK South

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#184]
A couple of weird errors when trying to register a patient following the BCDR testing

- Patient was created on the CPFT Server hosted on UK South (the normal server)
- Failover to UK-West (the patient was restored from backup)
- Instance reverted to UK South

I tried to register the patient. The first time I got "There is no patient with access key 'tijar-pogul-musom-hopog-mojiz-rufun-pijaz-sofon-s'. Have you entered the key correctly? The key validated fine.

The second time I got this error:

```

2021-06-25 14:32:30.353 [p4584.t140602192693056] camcops_server.cc_modules.client_api:ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 779, in _getter
    getter = self._metadata._getter
AttributeError: 'NoneType' object has no attribute '_getter'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/client_api.py", line 3255, in client_api
    resultdict = main_client_api(req)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/client_api.py", line 3205, in main_client_api
    ts = req.tabletsession
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    ts = req.tabletsession
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_request.py", line 468, in tabletsession
    new_cc_session = CamcopsSession.get_session_for_tablet(ts)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_session.py", line 218, in get_session_for_tablet
    session_token=ts.session_token)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/camcops_server/cc_modules/cc_session.py", line 291, in get_session
    filter(cls.last_activity_utc >= oldest_last_activity_allowed).\
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3397, in first
    ret = list(self[0:1])
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3171, in __getitem__
    return list(res)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 61, in instances
    for query_entity in query._entities
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 61, in <listcomp>
    for query_entity in query._entities
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 4397, in row_processor
    polymorphic_discriminator=self._polymorphic_discriminator,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 422, in _instance_processor
    getter = result._getter(col, False)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 781, in _getter
    return self._non_result(None, err)
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1241, in _non_result
    replace_context=err,
  File "/usr/share/camcops/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.

```

This got the patient details but failed to download the task schedule. When I hit the disk icon the task schedule loaded OK.

With the next patient I registered there were no problems.

**Comment by RudolfCardinal** [comment]
I think this ends up (line 287-292 of ``cc_session.py``) as a call to the SQLAlchemy ``first()`` method, and then a check if that is ``None`` or not. Since ``first()`` is expected to return ``None`` sometimes, but here it crashed, that sounds like a "deep in database" problem. I presume that makes it likely that it was related to the database unexpectedly changing state -- or connectability somehow? -- because of the server fallover. I don't know if we should be doing anything extra to cope with "your database breaks while you're running"...? Close as outside our control, or is some mitigation possible?

**Comment by martinburchell** [comment]
Thanks for looking. Looks like this isn't anything we can fix in the code at least. I guess we might not see this if the database was restored from the last know database SQL backup rather than the current state of the filesystem at the point of failure.

Closing...
