### ISSUE TITLE
Foreign key constraint fails when deleting a patient

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#35]
Do we need to delete the task index entries or set patient_pk to null before deleting the patient?

```
2019-09-19 12:12:31.325 [p30792.t139660768560896] camcops_server.cc_modules.cc_taskcollection:WARNING: Can't use index for non-current tasks
[19/Sep/2019:12:12:31] ENGINE InvalidRequestError("This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')\n[SQL: DELETE FROM patient WHERE patient._pk = %(_pk)s]\n[parameters: {'_pk': 1}]\n(Background on this error at: http://sqlalche.me/e/gkpj)",)
Traceback (most recent call last):
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 819, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1001, in _read_query_result
    result.read()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 965, in _read_packet
    packet.check_error()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/webview.py", line 3169, in delete_patient
    p.delete_with_dependants(req)
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_patient.py", line 771, in delete_with_dependants
    for pidnum in self.gen_patient_idnums_even_noncurrent():
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_patient.py", line 757, in gen_patient_idnums_even_noncurrent
    for live_pidnum in self.idnums:
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 276, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 682, in get
    value = self.callable_(state, passive)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 722, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 864, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 531, in all
    return list(self)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 429, in __iter__
    self.session._autoflush()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1587, in _autoflush
    util.raise_from_cause(e)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 624, in execute
    uow,
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 348, in delete_obj
    delete,
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1305, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 819, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1001, in _read_query_result
    result.read()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 965, in _read_packet
    packet.check_error()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')
[SQL: DELETE FROM patient WHERE patient._pk = %(_pk)s]
[parameters: {'_pk': 1}]
(Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cheroot/server.py", line 1273, in communicate
    req.respond()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cheroot/wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cherrypy/_cptree.py", line 302, in __call__
    return app(environ, start_response)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cardinal_pythonlib/wsgi/reverse_proxied_mw.py", line 553, in __call__
    return self.app(environ, start_response)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 260, in invoke_request
    request._process_finished_callbacks()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/request.py", line 147, in _process_finished_callbacks
    callback(self)
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_request.py", line 351, in end_sqlalchemy_session
    req._finish_dbsession()
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_request.py", line 390, in _finish_dbsession
    session.commit()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 491, in commit
    self._assert_active(prepared_ok=True)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')
[SQL: DELETE FROM patient WHERE patient._pk = %(_pk)s]
[parameters: {'_pk': 1}]
(Background on this error at: http://sqlalche.me/e/gkpj)

2019-09-19 12:12:31.921 [p30792.t139660768560896] cherrypy.error:ERROR: [19/Sep/2019:12:12:31] ENGINE InvalidRequestError("This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')\n[SQL: DELETE FROM patient WHERE patient._pk = %(_pk)s]\n[parameters: {'_pk': 1}]\n(Background on this error at: http://sqlalche.me/e/gkpj)",)
Traceback (most recent call last):
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 819, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1001, in _read_query_result
    result.read()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 965, in _read_packet
    packet.check_error()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/webview.py", line 3169, in delete_patient
    p.delete_with_dependants(req)
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_patient.py", line 771, in delete_with_dependants
    for pidnum in self.gen_patient_idnums_even_noncurrent():
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_patient.py", line 757, in gen_patient_idnums_even_noncurrent
    for live_pidnum in self.idnums:
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 276, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 682, in get
    value = self.callable_(state, passive)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 722, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 864, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 531, in all
    return list(self)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 429, in __iter__
    self.session._autoflush()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1587, in _autoflush
    util.raise_from_cause(e)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 624, in execute
    uow,
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 348, in delete_obj
    delete,
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1305, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 819, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1001, in _read_query_result
    result.read()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 965, in _read_packet
    packet.check_error()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')
[SQL: DELETE FROM patient WHERE patient._pk = %(_pk)s]
[parameters: {'_pk': 1}]
(Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cheroot/server.py", line 1273, in communicate
    req.respond()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cheroot/wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cherrypy/_cptree.py", line 302, in __call__
    return app(environ, start_response)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/cardinal_pythonlib/wsgi/reverse_proxied_mw.py", line 553, in __call__
    return self.app(environ, start_response)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/router.py", line 260, in invoke_request
    request._process_finished_callbacks()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/pyramid/request.py", line 147, in _process_finished_callbacks
    callback(self)
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_request.py", line 351, in end_sqlalchemy_session
    req._finish_dbsession()
  File "/home/martin/workspace/camcops/server/camcops_server/cc_modules/cc_request.py", line 390, in _finish_dbsession
    session.commit()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 491, in commit
    self._assert_active(prepared_ok=True)
  File "/home/martin/workspace/camcops/working/.server_ve/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`camcops`.`_idnum_index`, CONSTRAINT `fk__idnum_index_patient_pk` FOREIGN KEY (`patient_pk`) REFERENCES `patient` (`_pk`))')
[SQL: DELETE FROM patient WHERE patient._pk = %(_pk)s]
[parameters: {'_pk': 1}]
(Background on this error at: http://sqlalche.me/e/gkpj)


```

**Comment by RudolfCardinal** [comment]
Ah; yes! Need to delete the task index first (I guess ideally before deleting the task, though that is not a constraint-enforced FK).
